### ISSUE TITLE
variation template update?

### ISSUE THREAD

**Issue by laisimiao** [dawnyc/ROMTrack#7]
In
https://github.com/dawnyc/ROMTrack/blob/1d3b8a88be1f5aa40802c837528feaadd3d25619/lib/test/tracker/ROMTrack.py#L119
It seems you do not update the template for `forward_test()` function so that there are also no update for `self.k_vt and self.v_vt`
in
https://github.com/dawnyc/ROMTrack/blob/1d3b8a88be1f5aa40802c837528feaadd3d25619/lib/models/ROMTrack/Transformer.py#L264-L265
I think it is a little bit inconsistent with training phase(that its template are from two different frames), do you try update the template when using `forward_test()` function during inference?

**Comment by dawnyc** [comment]
We do not update the template, but I think we do update the variation token every time we assign 'k_t' to 'self.k_vt'. This is because 'k_t' is part of 'k' in each Attention layer, and mixed attention of 'template' and 'search' is conducted on 'x'. As depth of layer goes deeper, the 'k' part, which is the output of linear projection of 'x', will fuse search features into itself. So we save this 'k_t' as self.k_vt for next frame's tracking.

**Comment by laisimiao** [comment]
Yes, you are right, thanks.
